### PR TITLE
Feat: advise screen

### PR DESCRIPTION
**Pull request by D-Rosa99**
# Description 

In this PR I add the advice screen and given it style, I made a new file with the data because there is not any API for it, in COVID-RD the data is hard coded too

#### Linked issues:

Fixes [#46](https://trello.com/c/QpUiSJr3/46-advertisements-view)

#### Screenshots:

image

### CODE REVIEW

**Review by adnanjt — CHANGES_REQUESTED** [review]
Is app/components/List.js a New component or existing? This cant be changed if is done by MIT as is

**Comment by D-Rosa99** [comment]
> Is app/components/List.js a New component or existing? This cant be changed if is done by MIT as is

I think this component was created by @iocedano 
List.js is a existing component, I just changed how image source looks like because in the way it was wouldn't work with the bulletins and advice icons.

I think there are just bit changes that wouldn't change the workflow of the project

**Review by adnanjt — APPROVED** [review]
LGTM

**Comment by Faustrox** [comment]
LGTM

**Review by Faustrox — APPROVED** [review]
LGTM

**Pull request merged**
