### PR TITLE
Sponsors Screen

### PR DESCRIPTION
**Pull request by Faustrox**
**Description:** Added a new screen named Sponsors, also added buttons in Home Screen and Settings for go to that new screen.

**Linked issues:** [Ticket](https://trello.com/c/oMiZIk5R/148-create-an-auspiciadores-view-for-sponsors)

**Screenshots:**
photo5125125290123700385
Screenshot_2020-06-12-16-58-44-181_com optic covdr
Screenshot_2020-06-12-16-58-55-303_com optic covdr

**How to test:** Click on the button in the bottom of home screen or go to settings and press the button named "Sponsors" in the bottom, these buttons are going to send you  to Sponsors Screen. You can press the Sponsor's card that you want, that is going to send you to the page of corresponded Sponsor

### CODE REVIEW

**Review by inteljudajocu — CHANGES_REQUESTED** [review]
Assets are missing, cannot be tested

**Comment by Faustrox** [comment]
This PR need a change in the snapshots, I couldn't done it... I hope someone can help me in that, is with the snapshot of Settings. SOLVED

**Review by adnanjt — APPROVED** [review]
LGTM ready to go

**Review by inteljudajocu — APPROVED** [review]
LGTM, just don't edit the .gitignore file unnecessary in the future. If some assets or other types of files are in the .gitignore file and need to be uploaded just added them manually in that case.
For example git add app/asset/img/Filename

**Pull request merged**
