### PR TITLE
changin datePicker design on android

### PR DESCRIPTION
**Pull request by D-Rosa99**
#### Description:

I have changed the design of datePicker to another friendly one, I have used the one Facebook has used

#### Linked issues:

Fix: [140](https://trello.com/c/9OIiEeyQ/140-revisar-formato-de-fecha-del-form-para-que-sea-m%C3%A1s-end-user-friendly)

#### Screenshots:

image

#### How to test:

- `git pull && git checkout Fix/140-friendly-date-picker`
- Head over to report screen and press one of the option to start to fill it
- Check the date picker design

### CODE REVIEW

**Review by RutsSantos — APPROVED** [review]
Can the "Cancelar" and "Aceptar" be global translatable strings? besides that LGTM

**Comment by D-Rosa99** [comment]
> Can the "Cancelar" and "Aceptar" be global translatable strings? besides that LGTM

No, this is proper of the component, and I think is understandable in the way it is

**Review by inteljudajocu — COMMENTED** [review]
LGTM, arrived to a consensus about the translation to approve this

**Review by inteljudajocu — APPROVED** [review]

**Review by Faustrox — APPROVED** [review]
LGTM

**Pull request merged**
