### PR TITLE
New positive report screen

### PR DESCRIPTION
**Pull request by Faustrox**
#### Screenshots: 
photo5159290552372537494

### CODE REVIEW

**Review by JoseFcoEstrella — APPROVED** [review]
LGTM

**Comment by D-Rosa99** [comment]
There's a problem with the label `Report your symptoms` in english 

image

**Comment by D-Rosa99** [comment]
When I hit the `I Am Positive` button and entered my credential and hit continue the screen does not move to another screen
is this how supposed to behave?

Also, is not supposed to open a dialog card to ask me if I want to share my information with the ministry, because is not show it at all

**Comment by Faustrox** [comment]
> When I hit the `I Am Positive` button and entered my credential and hit continue the screen does not move to another screen
> is this how supposed to behave?
> 
> Also, is not supposed to open a dialog card to ask me if I want to share my information with the ministry, because is not show it at all

**Comment by Faustrox** [comment]
> When I hit the `I Am Positive` button and entered my credential and hit continue the screen does not move to another screen
> is this how supposed to behave?
> 
> Also, is not supposed to open a dialog card to ask me if I want to share my information with the ministry, because is not show it at all

The last is not concerned for this ticket, and the first... I let it that way because yesterday it was not very clear what need to do after, but my show show a dialog error. Remember that you need the token.

**Review by inteljudajocu — CHANGES_REQUESTED** [review]
Screen Shot 2020-06-26 at 9 05 27 AM

This happens as soon as you choose you're positive. If that's the desired behavior the card option to put the id is unnecessary else that dialog shouldn't be the first experience of that screen.

**Comment by Faustrox** [comment]
> Screen Shot 2020-06-26 at 9 05 27 AM
> 
> This happens as soon as you choose you're positive. If that's the desired behavior the card option to put the id is unnecessary else that dialog shouldn't be the first experience of that screen.

Solved

**Review by inteljudajocu — APPROVED** [review]

**Pull request merged**
